// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionConfigurationName
{
    internal sealed partial class Vsix
    {
        public const string Id = "f8b7f761-0afd-47d2-8f62-136c7dc50973";
        public const string Name = "Solution Configuration Name";
        public const string Description = @"A Visual Studio extension that sets SolutionConfiguration and SolutionPlatform build macros";
        public const string Language = "en-US";
        public const string Version = "1.0.8";
        public const string Author = "Francesco Pretto";
        public const string Tags = "";
    }
}
